version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sistemaws-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sistemaws-network

  # Banco de Produção
  unisystem-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: unisystem-prod
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - unisystem_data:/var/opt/mssql
    networks:
      - sistemaws-network

  # Banco de Desenvolvimento
  unisystem-dev-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: unisystem-dev
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1435:1433"
    volumes:
      - unisystem_dev_data:/var/opt/mssql
    networks:
      - sistemaws-network

volumes:
  sqlserver_data:
  unisystem_data:
  unisystem_dev_data:

networks:
  sistemaws-network:
    driver: bridge