version: '3.8'

services:
  # Banco de dados principal
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sistemaws-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - sistemaws-network
    # healthcheck:
    #   test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1' || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 60s

  # Aplicação .NET
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistemaws-api
    ports:
      - "7071:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UniSystem;User Id=sa;Password=YourStrong@Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - sistemaws-network
    volumes:
      - ./Sistemaws.WebApi/appsettings.json:/app/appsettings.json:ro

volumes:
  sqlserver_data:
  unisystem_data:
  unisystem_dev_data:

networks:
  sistemaws-network:
    driver: bridge